---
version: '3'

services:
    tempest:
        image: ghcr.io/marcorfilacarreras/tempest:latest
        container_name: tempest
        ports:
            - 127.0.0.1:6000:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./app.log:/app/app.log
            - ./db.sqlite:/app/db.sqlite
        env_file:
            - .env
        restart: unless-stopped

    nactite:
        image: ghcr.io/marcorfilacarreras/nactite:latest
        container_name: tempest-nactite
        volumes:
            - ./nactite/app.log:/app/requests.log
            - ./nactite/db.sqlite:/app/cache.db
        env_file:
            - ./nactite/.env
        restart: unless-stopped
        labels:
            - tempest.enable=true
            - tempest.name=Nactite
            - tempest.description=An SDK for some Intecat services and a website.
            - tempest.icon=https://cdn.shopify.com/s/files/1/0765/3372/7522/files/favicon.ico
            - tempest.readme=https://raw.githubusercontent.com/MarcOrfilaCarreras/nactite/refs/heads/master/README.md
            - tempest.tags=python3,flask,sdk
            - tempest.stats=Last updated:2025-02-03
